#!/usr/bin/env bash

delete() #$1 username
{
	sudo killall -u $1
	sudo userdel -f $1
	exit
}

main() #$1 username
{
	if [ "$#" -eq 1 ]
	then
		delete $1
		return 0
	else
		echo 'usage: ./02 username'
		return 64
	fi
}

main $1
